#pragma once

namespace cornus {

// #define CORNUS_DEBUG_SERVER_INOTIFY
// #define CORNUS_DEBUG_INOTIFY
// #define CORNUS_WAITED_FOR_WIDGETS
// #define CORNUS_SERVER_CLIPBOARD_DEBUG
// #define CORNUS_CLIPBOARD_CLIENT_DEBUG
// #define CORNUS_THROTTLE_IO
}
